apiVersion: v1
kind: Service
metadata:
  name: event-listener-service
  labels:
    app: eventtest
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: eventtest
  type: LoadBalancer
